### ISSUE TITLE
Saving world errors

### ISSUE THREAD

**Issue by bigrice1018** [asiekierka/ClassCacheTweakerMC#5] opened 2017-03-15 04:09 UTC
Everytime when opening the pause menu(press ESC)
The following errors shows up

[12:08:51] [Thread-55/INFO] [STDERR]: [pl.asie.classcachetweaker.ClassCache:save:337]: java.util.ConcurrentModificationException
[12:08:51] [Thread-55/INFO] [STDERR]: [pl.asie.classcachetweaker.ClassCache:save:337]: 	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
[12:08:51] [Thread-55/INFO] [STDERR]: [pl.asie.classcachetweaker.ClassCache:save:337]: 	at java.util.HashMap$ValueIterator.next(Unknown Source)
[12:08:51] [Thread-55/INFO] [STDERR]: [pl.asie.classcachetweaker.ClassCache:save:337]: 	at pl.asie.classcachetweaker.ClassCache.save(ClassCache.java:280)
[12:08:51] [Thread-55/INFO] [STDERR]: [pl.asie.classcachetweaker.ClassCache:save:337]: 	at pl.asie.classcachetweaker.ClassCache.access$100(ClassCache.java:31)
[12:08:51] [Thread-55/INFO] [STDERR]: [pl.asie.classcachetweaker.ClassCache:save:337]: 	at pl.asie.classcachetweaker.ClassCache$1.run(ClassCache.java:217)
[12:08:51] [Thread-55/INFO] [STDERR]: [pl.asie.classcachetweaker.ClassCache:save:337]: 	at java.lang.Thread.run(Unknown Source)

**Comment by asiekierka** [comment] 2017-03-15 05:54
Duplicate of https://github.com/asiekierka/ClassCacheTweakerMC/issues/4

**Closed as completed by asiekierka** 2017-03-15 05:54 UTC
